### PR TITLE
Write a tool to automatically fill out the go mod redirects

### PR DESCRIPTION
**Pull request by evankanderson**
This generates a bunch more redirects than we have, standardizes the format, and I think fixes the sample-controller import.

I wasn't quite sure what effect putting a `go.mod` at the top-level would have, so put it next to the tool, but I'd like some opinions.

/assign @mattmoor @n3wscott @RichieEscarez 

Next step:
* Figure out how to run this as a nightly action proposing PRs.

### CODE REVIEW

**Comment by mattmoor** [comment]
/lgtm
/hold

Holding in case you want more eyeballs on this.  If you make `./hack/update-codegen.sh` run this then two nice things will happen:
1. Verify codegen will block submits that break this, and
2. You'll automatically start getting nightly PRs (if website were in the mix, which is might not be)

**Comment by RichieEscarez** [comment]
looks like this is working = Everything in the `/static` folder is getting published to the site, and the `/tools` folder isn't (or at least not causing anything to break)

/lgtm

**Comment by evankanderson** [comment]
I'll probably do the `./hack/update-codegen.sh` as a separate PR, thanks for the tip!

**Pull request merged**
