### PR TITLE
Adding a link to katacoda tutorials

### PR DESCRIPTION
**Pull request by sbawaska**
Screen Shot 2021-01-12 at 9 50 22 PM

This links to the katacoda tutorials that are pending merge:
https://github.com/knative/docs/pull/3142

### CODE REVIEW

**Comment by omerbensaadon** [comment]
I am extremely curious on the click rate for this button. 

Even if this ends up being not the "ideal" solution in the long-run, the data behind how many folks click that button would be helpful. 

For a next iteration of this experiment, we may want to move the "In-Browser" tutorial to live on the Knative site and measure time-on-site as a result of this change.

**Comment by omerbensaadon** [comment]
@sbawaska can we embed Katacoda into the website...?

**Comment by RichieEscarez** [comment]
Adding the TOC for this type of change. 

Once upon a time there were lots of non Knative specific docs and code samples throughout the Knative docs library but that caused tons of maintenance issues among other things. Today there are these two sections that we have for linking to external tutorials/docs/codes samples:

https://knative.dev/docs/samples/#external-code-samples
https://knative.dev/community/samples/

Im not familiar with Katacoda but this feels like something different (maybe a new or different section?). I'd like the TOC to discuss and drive the guidelines about what and when to open the door to adding content to the main Knative page.

**Comment by sbawaska** [comment]
> @sbawaska can we embed Katacoda into the website...?

@omerbensaadon embedding is only allowed as a paid subscription.

**Comment by sbawaska** [comment]
@RichieEscarez and TOC members:
This change is in line with what Tekton does on their home page. The links highlighted in the screen shot point to katacoda tutorials. 
Screen Shot 2021-03-30 at 10 27 25 AM

**Comment by sbawaska** [comment]
The PR for the tutorials has now been merged knative/docs#3142

**Comment by markusthoemmes** [comment]
@sbawaska the entire website has meanwhile moved over to https://github.com/knative/docs/. Do you mind moving this over if you'd still want to do this?

**Pull request closed without merging**
