### PR TITLE
allow permanent links - redirect archived URL to latest

### LINKED ISSUE #25: Unable to create permanent link to docs for latest Knative release
Today https://www.knative.dev/docs/ points to docs for the 0.4 releases of Knative. Soon that same URL will point to 0.5. What I'd like to be able to do is create a permanent link to the docs for any specific Knative version, even the most recent release.

I can create a permanent link for older docs, like the 0.3 release, as the URL looks like https://www.knative.dev/v0.3-docs/

But for the current release the URL does not have the version number and thus I can't create a permanent link to docs for that version. Nor does manually typing in https://www.knative.dev/v0.4-docs/ work until v0.4 is no longer the current release.

### PR DESCRIPTION
**Pull request by RichieEscarez**
allow someone to create a permanent link to the latest version which is published to `/docs/`, so that link persists even after that content is archived (for example `/v#.#-docs/`)

fixes #25 

with this change, you can link to what the future "archived URL" will be, which will be redirected to the "latest version"

for each release, this file must be updated to the latest docs release version number

Example: 
todays latest version is `release-0.10` and the latest version is always published under the directory `/docs/*`

if you want to link specifically to only a topic in the v0.10 content, you can modify the URL to indicate the release version (future archive location) `/v0.10-docs/`, and that URL will redirect to `/docs/` until it gets archived to its permanent folder/archive location (`/v0.10-docs/`)

therefore `https://knative.dev/v0.10-docs/*` (or any path) gets redirected to `https://knative.dev/docs/*`(ie. `https://knative.dev/v0.10-docs/install/` -> `https://knative.dev/docs/install/`)

Live example from staging:

https://deploy-preview-101--knative.netlify.com/v0.10-docs/serving/accessing-logs/

(try other URLs by appending to `https://deploy-preview-101--knative.netlify.com/v0.10-docs/`)

### CODE REVIEW

**Comment by bbrowning** [comment]
From a functionality point-of-view, this solves the issue I originally opened. Holding off on an actual lgtm in case someone else from the docs teams wants to review before a merge gets triggered.

Thanks!

**Comment by RichieEscarez** [comment]
@samodell or @carieshmarie any feedback here?

**Comment by RichieEscarez** [comment]
Had to resolve the merge conflict (so took the opportunity to add more comments).

**Pull request merged**
