### PR TITLE
search/replace master with main

### PR DESCRIPTION
**Pull request by RichieEscarez**
All knative docs builds are broken since the repo branch changed from master to main.

Build logs https://app.netlify.com/sites/knative/deploys

### CODE REVIEW

**Review by csantanapr — APPROVED** [review]
thank you @RichieEscarez 
preview here https://6046e8c50475490007858794--knative.netlify.app

**Comment by csantanapr** [comment]
@evankanderson I think you need to approve this

**Comment by csantanapr** [comment]
I don't know why I can't

**Comment by evankanderson** [comment]
/approve

You need to be in OWNERS at the repo root is my guess...

**Pull request merged**
