### PR TITLE
Apply Docsy updates from the upstream

### LINKED ISSUE #224: Top page is hard to read on mobile
Top page is hard to read on mobile due to too broad margin on both sides.

e.g., on iPhone SE:

knative dev_(iPhone 5_SE)

### PR DESCRIPTION
**Pull request by tnir**
Improves user experience on mobile screens.

cf. google/docsy#344

Closes #224

### CODE REVIEW

**Comment by tcnghia** [comment]
It looks a lot better on mobile with the new smaller margin (https://deploy-preview-226--knative.netlify.app vs https://knative.dev). Thanks for the change.
/approve

@abrennan89 can you please also take a look? thanks

**Comment by RichieEscarez** [comment]
I dont have time to test this today but I want to add that this update also picks up the recently added ["click to copy" feature](https://github.com/google/docsy/pull/325) too (and fixes #57).

**Comment by RichieEscarez** [comment]
Clicking around in the staged version looks great (though ive not done it throughly). I would say the other thing to verify is that the local builds run fine too. 

And... Thanks @tnir !

**Comment by tcnghia** [comment]
@RichieEscarez I think the local build is validated in the workflow. Check out https://deploy-preview-226--knative.netlify.app

**Comment by RichieEscarez** [comment]
The localbuild.sh scripts work perfectly!

@tcnghia FYI, the local build uses Hugo and the Hugo server to run similar build scripts while the preview (linked above) is built through Hugo and Netlify. In the past, these builds did not behave the same and that led to lots of issues in our site. We might be past that now and I do hope thats the case but I still like to test that before we merge since not only do some contributors regularly use the localbuild.sh scripts but also one of our bots in the knative/docs repo uses it.

Thanks again @tnir 
(im also looking forward to trying out the click-to-copy feature and eventually adding that throughout our docs)

**Comment by tcnghia** [comment]
Thanks @RichieEscarez for explaining!

**Review by RichieEscarez — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
