### PR TITLE
Surface all samples on the Community page

### PR DESCRIPTION
**Pull request by RichieEscarez**
Add Samples to default Community landing page

Issue: https://github.com/knative/docs/issues/1213

### CODE REVIEW

**Comment by RichieEscarez** [comment]
PTAL: https://deploy-preview-35--knative.netlify.com/community/

Note that these changes depend on https://github.com/knative/docs/pull/1218 (ie new build samples and all samples pages)

**Comment by samodell** [comment]
@RichieEscarez  Right now, the headers "Share your expertise" and "Use and run" are floating around, semi-centered over the text below them, but not entirely. Could we left-align them above their text blocks, like "Learn and connect" and "Develop and contribute" are in the section above?

Otherwise, I really like this! The little icons in the lists are a nice touch.

**Comment by RichieEscarez** [comment]
> @RichieEscarez Right now, the headers "Share your expertise" and "Use and run" are floating around, semi-centered over the text below them, but not entirely. Could we left-align them above their text blocks, like "Learn and connect" and "Develop and contribute" are in the section above?
> 
> Otherwise, I really like this! The little icons in the lists are a nice touch.

Left justified the sub headers, PTAL

**Pull request merged**
