### PR TITLE
Add knative.dev/specs golang redirect

### PR DESCRIPTION
**Pull request by tayarani**
# Changes
Needed for https://github.com/knative/community/issues/499

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by tayarani** [comment]
@evankanderson

**Comment by tayarani** [comment]
@grantr @vaikas

**Comment by tayarani** [comment]
ping @vaikas

**Comment by vaikas** [comment]
Sorry, slipped through the cracks.

**Pull request merged**
