### PR TITLE
Adding container-freezer aliases

### PR DESCRIPTION
**Pull request by psschwei**
# Changes

- adding aliases for container-freezer

Part of https://github.com/knative/community/issues/742

### CODE REVIEW

**Comment by evankanderson** [comment]
Ugh, we need to update our docs... these files are now in the docs repo: https://github.com/knative/docs/blob/main/golang/README.md

**Comment by julz** [comment]
came here to say what @evankanderson said 11 seconds ago :)

**Comment by psschwei** [comment]
Easy enough... I'll open an issue for the doc fix after I make this PR in the docs repo

**Comment by psschwei** [comment]
Actually, looks like the docs / issue template _were_ updated, but after this issue was created (and hence why I opened this against the wrong repo)

**Pull request closed without merging**
