### PR TITLE
Add knative.dev/kn-plugin-admin redirects

### PR DESCRIPTION
**Pull request by evankanderson**
/assign @rhuss

### CODE REVIEW

**Comment by evankanderson** [comment]
Ref: https://github.com/knative/client-contrib/issues/75

**Review by rhuss — COMMENTED** [review]
Thanks ! Looks good to me, although kn-plugin-admin is not really intended to be included ever as a golang dependency, so no need for a vanity domain.

However, if we want to add *all* sandbox repos as vanity domains, that make sense for consistencies sake.

**Comment by rhuss** [comment]
@evankanderson sorry for the delay. If you think we should merge that, happy to lgtm is. but just wanted to be sure, as I'm not 100% convinced this is needed (and if needed, we could still add this later, too)

**Comment by evankanderson** [comment]
Right now, I'm inclined towards consistency.

**Review by mattmoor — COMMENTED** [review]
/lgtm

**Pull request merged**
