### PR TITLE
Upgrade to Hugo 0.74.3, fix knative/docs#2706

### PR DESCRIPTION
**Pull request by evankanderson**
Fixes https://github.com/knative/docs/issues/2706

Follow on to #196 

Deploy preview: https://deploy-preview-196--knative.netlify.app/

Sample page from https://github.com/knative/docs/issues/2706

https://deploy-preview-196--knative.netlify.app/docs/eventing/samples/kubernetes-event-source/#deployment-steps

Compare with:

https://knative.dev/docs/eventing/samples/kubernetes-event-source/#deployment-steps

### CODE REVIEW

**Comment by evankanderson** [comment]
This needs #198 to merge first.

**Comment by evankanderson** [comment]
Fixes https://github.com/knative/docs/issues/2706

**Comment by RichieEscarez** [comment]
This needs a rebase (even though Prow thinks otherwise). These errors are causing the build to fail:

```
2:07:21 PM: Building sites … WARN 2020/08/17 21:07:21 Page.Dir is deprecated and will be removed in a future release. Use .File.Dir
2:07:30 PM: Total in 10079 ms
2:07:30 PM: Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "stdin", line 8, col 1: File to import not found or unreadable: ../vendor/Font-Awesome//web-fonts-with-css/scss/fontawesome.scss.
```

**Pull request merged**
