### PR TITLE
Update config.toml

### PR DESCRIPTION
**Pull request by omerbensaadon**
Changing Analytics to a knative.team owned account

### CODE REVIEW

**Comment by omerbensaadon** [comment]
Closes https://github.com/knative/community/issues/89#issuecomment-781526818

**Comment by evankanderson** [comment]
Is this ready to be approved?

/assign @evankanderson

**Comment by omerbensaadon** [comment]
Yes!

**Comment by RichieEscarez** [comment]
Sorry I missed the meeting where this was all discussed but I believe (from my exchange with April) that we need to have both Google Analytics accounts tied to the site.

**Comment by vaikas** [comment]
@RichieEscarez @thisisnotapril what does that mean in practical terms? Just trying to understand the need for it as well as what impact does this have? Is this akin to mirroring the data into Google analytics account (for account restrictions, or something I'd reckon?). Also does this mean that we wouldn't lose the old data? Again, just trying to understand :)

**Comment by RichieEscarez** [comment]
To move forward at this point, someone would need to test and get Analytics working for both account IDs. 

WRT restrictions: Basically, external access to the internal Google tool is not allowed. That includes exporting all data from there. I can however extract anonymous data and share that like ive done for past requests. Here are those reports: https://drive.google.com/corp/drive/folders/16ozmyon22Uz2K0il32-gTEaLR4xyv7zM

Per the [Knative.dev privacy policy](https://policies.google.com/privacy) (the same standard Google Privacy policy), the current internal Analytics account only contains data for the last 14 mns (everything before that has been automatically deleted): https://support.google.com/analytics/answer/7667196?hl=en

Do let me know if there are other metrics that you want from the last 14 mns and I can upload that report to the shared drive.

Per the two different Google Analytics accounts, I think that was something that came out of the TOC - add a separate account for Knative members.

**Comment by omerbensaadon** [comment]
Ack on all above, will reach out to you w/ requests sometime in the next few weeks... 

I was under the impression that it was to move the analytics from a Google-owned account to a community-owned account...?

**Comment by csantanapr** [comment]
My impression was the same that there was going to be a single analytics account owned by the community under Knative team Google account and not longer Google owned

this way we have access to the analytics tools and we can get to the data directly fro. The dashboard makes it easier to filter and analyze with a web app instead of screenshots

**Comment by vaikas** [comment]
@thisisnotapril @csantanapr was there anything else that we needed here except add both IDs?

**Comment by RichieEscarez** [comment]
Add status/notes here incase it might help.

After spending a little time researching this. It looks like default Hugo/Docsy will give us this today (using this config.yaml file):

```
<script type="application/javascript">
 var doNotTrack = false;
 if (!doNotTrack) {
 window.ga=window.ga\|\|function(){(ga.q=ga.q\|\|[]).push(arguments)};ga.l=+new Date;
 ga('create', 'UA-148338258-1', 'auto');
 ga('send', 'pageview');
 }
 </script>
 <script async src='https://www.google-analytics.com/analytics.js'></script>
```

Per the instructions here: https://developers.google.com/analytics/devguides/collection/analyticsjs/display-features#using-multiple-trackers

We need to modify our site template to give us this instead (both IDs and the `require` elements too):
```
// Google ID: UA-148338258-1
ga('create', 'UA-148338258-1', {name: 'google'});
ga('google.require', 'displayfeatures');
ga('foo.send', 'pageview');

// Knative ID: G-YRMNFYE32R
ga('create', 'G-YRMNFYE32R', {name: 'knative'});
ga('knative.require', 'displayfeatures');
ga('knative.send', 'pageview');
```

Looking at how Hugo injects the Id in the config.yaml, we might need to create our own custom shortcode to be able to specify the required parameters for using multiple ids (`ga('google.require', 'displayfeatures');` and `ga('knative.require', 'displayfeatures');`).

Reference: https://gohugo.io/templates/internal/#google-analytics

**Comment by csantanapr** [comment]
@vaikas what we need is to include the 2 account IDs to Hugo 

thanks @RichieEscarez

**Comment by csantanapr** [comment]
@RichieEscarez  I proposed that we close this PR and that you do the changes to add the 2 Google analytics IDs.

Based on what you shared it looks like you have the knowledge on what needs to be done
https://github.com/knative/website/pull/252#issuecomment-786963159
>Adding status/notes here incase it might help.

After spending a little time researching this. It looks like default Hugo/Docsy will give us this today (using this config.yaml file):

<script type="application/javascript">
 var doNotTrack = false;
 if (!doNotTrack) {
 window.ga=window.ga\|\|function(){(ga.q=ga.q\|\|[]).push(arguments)};ga.l=+new Date;
 ga('create', 'UA-148338258-1', 'auto');
 ga('send', 'pageview');
 }
 </script>
 <script async src='https://www.google-analytics.com/analytics.js'></script>
Per the instructions here: https://developers.google.com/analytics/devguides/collection/analyticsjs/display-features#using-multiple-trackers

We need to modify our site template to give us this instead (both IDs and the require elements too):

// Google ID: UA-148338258-1
ga('create', 'UA-148338258-1', {name: 'google'});
ga('google.require', 'displayfeatures');
ga('google.send', 'pageview');

// Knative ID: G-YRMNFYE32R
ga('create', 'G-YRMNFYE32R', {name: 'knative'});
ga('knative.require', 'displayfeatures');
ga('knative.send', 'pageview');
Looking at how Hugo injects the Id in the config.yaml, we might need to create our own custom shortcode to be able to specify the required parameters for using multiple ids (ga('google.require', 'displayfeatures'); and ga('knative.require', 'displayfeatures');).

Reference: https://gohugo.io/templates/internal/#google-analytics

**Comment by RichieEscarez** [comment]
I can prioritize this over the "docs contributor" docs but schedule wise, I won't have bandwidth until next week. When I do start, ill mark this close and send out a PR. 

(FYI, our Hugo template site generator is Golang based so that might help other folks here if interested, and if someone does get to this first, here is the page about creating [shortcodes](https://gohugo.io/templates/shortcode-templates/) - also see our other [Knative custom shortcodes](https://github.com/knative/website/tree/master/layouts/shortcodes).)

**Comment by RichieEscarez** [comment]
Replacing this PR with https://github.com/knative/website/pull/262

**Pull request closed without merging**
