### PR TITLE
Remove README->index renames

### LINKED ISSUE #230: Readmes are being removed and content is added in _index.md
Content in _index.md files must not include the .md file extensions which is not a valid Markdown link and causes the Markdown link checker to always report a broken link (ie. with the .md, the link points to a non-existent folder).

The doc builds were initially set up to ignore _index.md files but now that README.md files are being removed and content is being directly added in the _index.md files, the build needs to accommodate these files.

https://github.com/knative/website/blob/master/scripts/processsourcefiles.sh#L109

This type of change would only work if all _index.md files are converted - ie. remove ALL READMEs and relocate all their content.

This issue surfaced here: https://github.com/knative/docs/pull/2840

### PR DESCRIPTION
**Pull request by evankanderson**
# Changes

- 🧹  Remove renames of `README.md` to `_index.md` or `index.md`. Instead, just report in the build script if this happens, so we can clean them up. Simplifies the build process and makes it easier to (for example) just build directly from the sources instead of needing additional pre-processing.

/kind cleanup

Fixes #https://github.com/knative/docs/pull/3286
Fixes #230

### CODE REVIEW

**Comment by evankanderson** [comment]
/hold

I don't want to submit this until after I see what the Netlify build looks like/complains about.

**Comment by evankanderson** [comment]
```
4:01:22 PM: ------ CONVERT FULLY QUALIFIED REPO URLS TO RELATIVE ------
4:01:22 PM: Converting all fully-qualified Knative URLs to relative URLs...
4:01:24 PM: Converting all links in GitHub source files to Hugo supported relative links...
4:01:26 PM: Converting all standalone README.md files to index.md...
4:01:27 PM: BARE README AT opt/build/repo/content/en/third_party/VENDOR-LICENSE/github.com/eclipse/paho.mqtt.golang, WILL NOT BE RENDERED.
4:01:27 PM: Copying the override files into the /content/ folder
```

/approve
/unhold

**Comment by evankanderson** [comment]
Sample site (including `community`) seems to be working okay:

https://deploy-preview-259--knative.netlify.app/

**Comment by abrennan89** [comment]
/lgtm
YOLO

**Pull request merged**
