### PR TITLE
updating resources folder, build script, and build params

### PR DESCRIPTION
**Pull request by RichieEscarez**
Found that you should always delete 'public' and 'resources' folders/artifacts from the "hugo server" local testing server.

- Updated resources folder from clean "hugo" only command build
- Added "development" docs version (content from 'master' branch)
- Fix base URLs to use custom domain (replace netlify URL with knative.dev)

### CODE REVIEW

**Comment by carieshmarie** [comment]
What happens if you don't delete the public and resources folders?

**Comment by RichieEscarez** [comment]
Ryan caught and help me realize that the resources folder (only necessary to upload while Netlify figures out how to support the Extended version of Hugo) includes a bunch of unnecessary files. While testing that, I noticed that the Hugo server tries to be efficient and will pull from the locally built public folder (therefore the resources file might not include the latest changes since the local server reuses the cache).

**Comment by RichieEscarez** [comment]
@samodell PTAL 

Sorry, mindlessly copied over code to "clone master" but i havent updated master for the site (thus the failed builds).

Ive changed this a bit to just duplicate v3 docs into multiple versions to verify it works on the production server.

Successful staging build is here: https://deploy-preview-9--knative.netlify.com/docs/
(note: dont navigate around on that preview because it builds with the "staging" branch and needs to be updated with all the other changes from master (next PR ive got coming))

**Pull request merged**
